// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDckoY1YdNMRkx18ylG3ZBje4cLt4Ks1FA',
    appId: '1:762243564655:web:46b1e14895772bbb9b799a',
    messagingSenderId: '762243564655',
    projectId: 'moodmap-20031',
    authDomain: 'moodmap-20031.firebaseapp.com',
    storageBucket: 'moodmap-20031.appspot.com',
    measurementId: 'G-2VN0M3T2W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASiYLtU2ZYOxbpRcJ__KBNzimJQkQw9vc',
    appId: '1:762243564655:android:faa8bba5ac8f968a9b799a',
    messagingSenderId: '762243564655',
    projectId: 'moodmap-20031',
    storageBucket: 'moodmap-20031.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB38lE3IKvQpZzMpFucPhzKeyTu8qDMAWo',
    appId: '1:762243564655:ios:52ded86d3a106b629b799a',
    messagingSenderId: '762243564655',
    projectId: 'moodmap-20031',
    storageBucket: 'moodmap-20031.appspot.com',
    iosClientId: '762243564655-6p57084jbm3fku1uu24tbcendlftfknf.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB38lE3IKvQpZzMpFucPhzKeyTu8qDMAWo',
    appId: '1:762243564655:ios:52ded86d3a106b629b799a',
    messagingSenderId: '762243564655',
    projectId: 'moodmap-20031',
    storageBucket: 'moodmap-20031.appspot.com',
    iosClientId: '762243564655-6p57084jbm3fku1uu24tbcendlftfknf.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodmap',
  );
}
